### ISSUE TITLE
I got the error like below

### ISSUE THREAD

**Issue by DuckLL** [cebrusfs/gdb217#2]
```
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
Traceback (most recent call last):
  File "/217gdb/pwndbg/commands/__init__.py", line 54, in __call__
    return self.function(*args, **kwargs)
  File "/217gdb/pwndbg/commands/__init__.py", line 112, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/217gdb/pwndbg/commands/context.py", line 55, in context
    sys.stdout.write(line + '\n')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-16: ordinal not in range(128)
```

I used the docker image of dm4tw/ctf-box.
I installed gdb and clone the 217gdb.
Running setup.sh have no problems.
But, after I set a break point, and run the program, the error will come up.
Is that environment has some problem?

**Comment by cebrusfs** [comment]
It seems that it is the encoding issue of unicode character which is used in banner.
Does your GDB use python 2 as its python interpreter?

Update: sorry that I click the wrong button. Orz

**Comment by cebrusfs** [comment]
I don't have an enviroment with gdb used python2. Could you try to fix this issue by yourself and give me some advice or even a PR?
I believe that this is cause by d0f719fa7bcdc9de6a7839338d95a9c629762f7c. You can see that `fill_char` is a unicode character.

**Comment by DuckLL** [comment]
My GDB used python3.

```
217gdb> py
>import sys
>print (sys.version)
>end
3.4.3 (default, Oct 14 2015, 20:31:36)
[GCC 4.8.4]
```

I am trying to fix this problem.
`fill_char` is not friendly. :(
I changed `fill_char` from `u'<E2><94><80>'` to `u'-'` , seem good but still come up error sometime (promgram execued `jle` instraction).
May you take a screenshot, let me know how the ui work in normally.

**Comment by cebrusfs** [comment]
Do you mean you fix this issue by storing the source code with the unicode encoding instead of UTF-8?

Sorry that I will go aboard for some CTF competition and may not able to support in this weekend.

There are the other parts have used unicode character.

Like this,
https://github.com/cebrusfs/217gdb/blob/master/pwndbg/disasm/color.py#L66
This will add some indicator when conditional jump is taken.

**Comment by cebrusfs** [comment]
Rebased from upstream recently. This issue may be outdated and fixed by upstream? Closed.
